import type { Metadata } from "next";
import { Suspense } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarServer from "@/components/NavbarServer";
import Footer from "@/components/Footer";
import Loading from "@/app/loading"



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CloudTenants -ERP Software Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <section className="m-0 p-0 scroll-smooth box-border">
        <NavbarServer />
        <Suspense fallback={<Loading />}>
        {children}
</Suspense>

        <Footer />
        </section>
      </body>
    </html>
  );
}
